name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger the deployment when changes are pushed to the main branch
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./lambda_package/

      # Step 4: Package all files for Lambda
      - name: Package all files
        run: |
          # You can also exclude certain files like tests, docs, etc., by modifying this command
          rsync -av --exclude 'lambda_package' ./ ./lambda_package/

          # Zip everything into a deployment package
          cd lambda_package
          zip -r ../lambda_package.zip .


      # Step 5: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: |
          pip install awscli
          aws lambda update-function-code \
            --function-name email-to-sheets \
            --zip-file fileb://lambda_package.zip
